
modLoader="javafml" #mandatory

loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All Rights Reserved"

[[mods]] #mandatory
# The modid of the mod
modId="darkestsouls" #mandatory
# The version number of the mod
version="1.2.2.1" #mandatory
# A display name for the mod
displayName="Darkest Souls" #mandatory
logoFile="banner_small_final.png" #optional
authors="Nitespring" #optional
description='''Miyazaki's Feet'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.darkestsouls]] #optional
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.darkestsouls]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.darkestsouls]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4.7,)"
    ordering="NONE"
    side="BOTH"
